---
title: "Recording spectra"
author: "Annebelle"
date: "2023-12-05"
output: html_document
---

```{r}
file<-list.files(path="G:/My Drive/Wadden fish sounds/Data analysis/Spectra/")
filetype<-"TOL"
file.list<-grepl(filetype,file,fixed=TRUE)
file.WC<-file[file.list]
setwd("G:/My Drive/Wadden fish sounds/Data analysis/Spectra/")

RES<-NULL
for(n in 1:length(file.WC)){
  setwd("G:/My Drive/Wadden fish sounds/Data analysis/Spectra/")
  dat<-read.csv(file.WC[n])
  titel<-file.WC[n]
  tel<-length(dat[,1])
  dat$file<-rep(titel,tel)
  loc<-strsplit(titel,"_","]",2)
  dat$Block<-rep(loc[[1]][1],tel)
  dat$Reef<-rep(loc[[1]][2],tel)
  dat$Deployment<-rep(loc[[1]][3],tel)
  
  if(length(names(dat))>28){ #for some files the frequency threshold was set at 20 Hz instead of 50 Hz, so there are more columns.
    dat<-dat[,c(1,6:32)]
  }
    
  RES<-rbind(RES,dat)
}
```
```{r}
require(tidyverse)
table(RES$Block,RES$Reef,RES$Deployment)
temp<-RES
temp$StartDate <- sapply(strsplit(as.character(temp$yyyy.mm.ddTHH.MM.SSZ), "T"), "[", 1)
temp$StartTime <- sapply(strsplit(as.character(temp$yyyy.mm.ddTHH.MM.SSZ), "T"), "[", 2)
temp$StartTime <- sapply(strsplit(as.character(temp$StartTime), "Z"), "[", 1)
temp2<-unite(temp,"startdatetime",c("StartDate","StartTime"),sep=" ")
temp2$Start<-as.POSIXct(temp2$startdatetime,format="%Y-%m-%d %H:%M:%S")
RES<-temp2

require(ggplot2)
ggplot(data=RES,aes(x=Start,y=TOL_125))+geom_line()+geom_line(aes(x=Start,y=TOL_63),colour="blue")+geom_line(aes(x=Start,y=TOL_400),colour="red")+facet_grid(.~Block+Reef)+theme(text = element_text(family="serif"))

ggplot(data=subset(RES,Deployment=="05"),aes(x=Start,y=TOL_125))+geom_line(aes(colour=Block))+facet_grid(.~Reef)
ggplot(data=subset(RES,Deployment=="06"),aes(x=Start,y=TOL_125))+geom_line(aes(colour=Block))+facet_grid(.~Reef)
ggplot(data=subset(RES,Deployment=="07"),aes(x=Start,y=TOL_125))+geom_line(aes(colour=Block))+facet_grid(.~Reef)
ggplot(data=subset(RES,Deployment=="08"),aes(x=Start,y=TOL_125))+geom_line(aes(colour=Block))+facet_grid(.~Reef)
ggplot(data=subset(RES,Deployment=="09"),aes(x=Start,y=TOL_125))+geom_line(aes(colour=Block))+facet_grid(.~Reef)
ggplot(data=subset(RES,Deployment=="10"),aes(x=Start,y=TOL_125))+geom_line(aes(colour=Block))+facet_grid(.~Reef)
ggplot(data=subset(RES,Deployment=="11"),aes(x=Start,y=TOL_125))+geom_line(aes(colour=Block))+facet_grid(.~Reef)
ggplot(data=subset(RES,Deployment=="12"),aes(x=Start,y=TOL_125))+geom_line(aes(colour=Block))+facet_grid(.~Reef)
ggplot(data=subset(RES,Deployment=="13"),aes(x=Start,y=TOL_125))+geom_line(aes(colour=Block))+facet_grid(.~Reef)
ggplot(data=subset(RES,Deployment=="14"),aes(x=Start,y=TOL_125))+geom_line(aes(colour=Block))+facet_grid(.~Reef)
```

```{r}
LAUW1_ON_05<-read.csv("G:/My Drive/Wadden fish sounds/Data analysis/LAUW2_OFF_05_BB_1h.csv")
head(LAUW1_ON_05)
require(ggplot2)

temp<-LAUW1_ON_05
temp$StartDate <- sapply(strsplit(as.character(temp$yyyy.mm.ddTHH.MM.SSZ), "T"), "[", 1)
temp$StartTime <- sapply(strsplit(as.character(temp$yyyy.mm.ddTHH.MM.SSZ), "T"), "[", 2)
temp$StartTime <- sapply(strsplit(as.character(temp$StartTime), "Z"), "[", 1)
temp2<-unite(temp,"startdatetime",c("StartDate","StartTime"),sep=" ")
temp2$Start<-as.POSIXct(temp2$startdatetime,format="%Y-%m-%d %H:%M:%S")
LAUW1_ON_05<-temp2
head(LAUW1_ON_05)

ggplot(data=LAUW1_ON_05,aes(x=Start,y=TOL_125))+geom_line()+geom_line(aes(x=Start,y=TOL_63),colour="blue")+geom_line(aes(x=Start,y=TOL_400),colour="red")
ggplot(data=LAUW1_ON_05,aes(x=Start,y=BB_50.12000))+geom_line()
```

```{r}
file<-list.files(path="G:/My Drive/Wadden fish sounds/Data analysis/Spectra/")
filetype<-"10min"
file.list<-grepl(filetype,file,fixed=TRUE)
file.WC<-file[file.list]
setwd("G:/My Drive/Wadden fish sounds/Data analysis/Spectra/")

BB<-NULL
for(n in 1:length(file.WC)){
  setwd("G:/My Drive/Wadden fish sounds/Data analysis/Spectra/")
  dat<-read.csv(file.WC[n])
  titel<-file.WC[n]
  tel<-length(dat[,1])
  dat$file<-rep(titel,tel)
  loc<-strsplit(titel,"_","]",2)
  dat$Block<-rep(loc[[1]][1],tel)
  dat$Reef<-rep(loc[[1]][2],tel)
  dat$Deployment<-rep(loc[[1]][3],tel)
  
  #if(length(names(dat))>28){ #for some files the frequency threshold was set at 20 Hz instead of 50 Hz, so there are more columns.
   # dat<-dat[,c(1,6:32)]
  #}
    
  BB<-rbind(BB,dat)
}
```

```{r}
require(tidyverse)
table(BB$Block,BB$Reef,BB$Deployment)
temp<-BB
temp$StartDate <- sapply(strsplit(as.character(temp$yyyy.mm.ddTHH.MM.SSZ), "T"), "[", 1)
temp$StartTime <- sapply(strsplit(as.character(temp$yyyy.mm.ddTHH.MM.SSZ), "T"), "[", 2)
temp$StartTime <- sapply(strsplit(as.character(temp$StartTime), "Z"), "[", 1)
temp2<-unite(temp,"startdatetime",c("StartDate","StartTime"),sep=" ")
temp2$Start<-as.POSIXct(temp2$startdatetime,format="%Y-%m-%d %H:%M:%S")
BB<-temp2

ggplot(data=BB,aes(x=Start,y=BB_50.12000))+geom_line(aes(colour=Reef))+facet_grid(.~Block)
```
